version: "2"
run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - path: gen/
        linters:
          - all

formatters:
  enable:
    - gofumpt
