# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.semantic.v1 import semantic_pb2 as memsidecar_dot_semantic_dot_v1_dot_semantic__pb2


class SemanticStub:
    """Semantic provides embed-and-search over arbitrary records, scoped by
    namespace. Every namespace is bound to a single embedding model at config
    time. Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upsert = channel.unary_unary(
                '/memsidecar.semantic.v1.Semantic/Upsert',
                request_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertRequest.SerializeToString,
                response_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/memsidecar.semantic.v1.Semantic/Search',
                request_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchRequest.SerializeToString,
                response_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/memsidecar.semantic.v1.Semantic/Delete',
                request_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteRequest.SerializeToString,
                response_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Expire = channel.unary_unary(
                '/memsidecar.semantic.v1.Semantic/Expire',
                request_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireRequest.SerializeToString,
                response_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireResponse.FromString,
                _registered_method=True)


class SemanticServicer:
    """Semantic provides embed-and-search over arbitrary records, scoped by
    namespace. Every namespace is bound to a single embedding model at config
    time. Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def Upsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Expire(self, request, context):
        """Expire applies a lifecycle action to every record matching a metadata
        filter, in one bounded server-side operation (ADR-0003, U3). max_rows caps
        the affected set so maintenance stays localized.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertRequest.FromString,
                    response_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchRequest.FromString,
                    response_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteRequest.FromString,
                    response_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteResponse.SerializeToString,
            ),
            'Expire': grpc.unary_unary_rpc_method_handler(
                    servicer.Expire,
                    request_deserializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireRequest.FromString,
                    response_serializer=memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.semantic.v1.Semantic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.semantic.v1.Semantic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Semantic:
    """Semantic provides embed-and-search over arbitrary records, scoped by
    namespace. Every namespace is bound to a single embedding model at config
    time. Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.semantic.v1.Semantic/Upsert',
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertRequest.SerializeToString,
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.semantic.v1.Semantic/Search',
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchRequest.SerializeToString,
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.semantic.v1.Semantic/Delete',
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteRequest.SerializeToString,
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Expire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.semantic.v1.Semantic/Expire',
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireRequest.SerializeToString,
            memsidecar_dot_semantic_dot_v1_dot_semantic__pb2.ExpireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
