# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.episodic.v1 import episodic_pb2 as memsidecar_dot_episodic_dot_v1_dot_episodic__pb2


class EpisodicStub(object):
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/memsidecar.episodic.v1.Episodic/Append',
                request_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.SerializeToString,
                response_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Range = channel.unary_stream(
                '/memsidecar.episodic.v1.Episodic/Range',
                request_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.SerializeToString,
                response_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
                _registered_method=True)
        self.Tail = channel.unary_stream(
                '/memsidecar.episodic.v1.Episodic/Tail',
                request_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.SerializeToString,
                response_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
                _registered_method=True)


class EpisodicServicer(object):
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Range(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EpisodicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.FromString,
                    response_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.SerializeToString,
            ),
            'Range': grpc.unary_stream_rpc_method_handler(
                    servicer.Range,
                    request_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.FromString,
                    response_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.SerializeToString,
            ),
            'Tail': grpc.unary_stream_rpc_method_handler(
                    servicer.Tail,
                    request_deserializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.FromString,
                    response_serializer=memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.episodic.v1.Episodic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.episodic.v1.Episodic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Episodic(object):
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.episodic.v1.Episodic/Append',
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.SerializeToString,
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Range(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memsidecar.episodic.v1.Episodic/Range',
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.SerializeToString,
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memsidecar.episodic.v1.Episodic/Tail',
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.SerializeToString,
            memsidecar_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
