# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.graph.v1 import graph_pb2 as memsidecar_dot_graph_dot_v1_dot_graph__pb2


class GraphStub:
    """Graph provides relationship-aware recall: node/edge upserts and bounded,
    structured traversal, scoped by namespace (ADR-0002). It FRONTS graph
    engines — it does not implement storage, indexing, a query planner, a
    query language, or any reasoning/entity-resolution. Traversal is always
    bounded server-side. Every RPC requires a capability token in the gRPC
    metadata key "x-memsidecar-capability" with value "Bearer <token>".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertNodes = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/UpsertNodes',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesResponse.FromString,
                _registered_method=True)
        self.UpsertEdges = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/UpsertEdges',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/GetNode',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.Node.FromString,
                _registered_method=True)
        self.Neighbors = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/Neighbors',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/Traverse',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.TraverseRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.Subgraph.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/DeleteNode',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)
        self.DeleteEdge = channel.unary_unary(
                '/memsidecar.graph.v1.Graph/DeleteEdge',
                request_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.SerializeToString,
                response_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.FromString,
                _registered_method=True)


class GraphServicer:
    """Graph provides relationship-aware recall: node/edge upserts and bounded,
    structured traversal, scoped by namespace (ADR-0002). It FRONTS graph
    engines — it does not implement storage, indexing, a query planner, a
    query language, or any reasoning/entity-resolution. Traversal is always
    bounded server-side. Every RPC requires a capability token in the gRPC
    metadata key "x-memsidecar-capability" with value "Bearer <token>".
    """

    def UpsertNodes(self, request, context):
        """Writes — idempotent upserts keyed by caller-supplied ids.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Reads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Neighbors(self, request, context):
        """1-hop, filtered
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """bounded multi-hop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Deletes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertNodes,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesResponse.SerializeToString,
            ),
            'UpsertEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertEdges,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.GetNodeRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.Node.SerializeToString,
            ),
            'Neighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.Neighbors,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.TraverseRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.Subgraph.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'DeleteEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdge,
                    request_deserializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.FromString,
                    response_serializer=memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.graph.v1.Graph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.graph.v1.Graph', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Graph:
    """Graph provides relationship-aware recall: node/edge upserts and bounded,
    structured traversal, scoped by namespace (ADR-0002). It FRONTS graph
    engines — it does not implement storage, indexing, a query planner, a
    query language, or any reasoning/entity-resolution. Traversal is always
    bounded server-side. Every RPC requires a capability token in the gRPC
    metadata key "x-memsidecar-capability" with value "Bearer <token>".
    """

    @staticmethod
    def UpsertNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/UpsertNodes',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/UpsertEdges',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.UpsertEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/GetNode',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.GetNodeRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.Node.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Neighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/Neighbors',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.NeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/Traverse',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.TraverseRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.Subgraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/DeleteNode',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.graph.v1.Graph/DeleteEdge',
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.SerializeToString,
            memsidecar_dot_graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
