# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.artifact.v1 import artifact_pb2 as memsidecar_dot_artifact_dot_v1_dot_artifact__pb2


class ArtifactStub:
    """Artifact provides blob storage with metadata, scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Put is client-streaming: the first message must carry PutInit, every
    subsequent message must carry PutChunk. Get is server-streaming: the
    first message carries GetHeader (metadata), every subsequent message
    carries GetChunk.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.stream_unary(
                '/memsidecar.artifact.v1.Artifact/Put',
                request_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutRequest.SerializeToString,
                response_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_stream(
                '/memsidecar.artifact.v1.Artifact/Get',
                request_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetRequest.SerializeToString,
                response_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/memsidecar.artifact.v1.Artifact/Stat',
                request_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatRequest.SerializeToString,
                response_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/memsidecar.artifact.v1.Artifact/Delete',
                request_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteRequest.SerializeToString,
                response_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_stream(
                '/memsidecar.artifact.v1.Artifact/List',
                request_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ListRequest.SerializeToString,
                response_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ArtifactMeta.FromString,
                _registered_method=True)


class ArtifactServicer:
    """Artifact provides blob storage with metadata, scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Put is client-streaming: the first message must carry PutInit, every
    subsequent message must carry PutChunk. Get is server-streaming: the
    first message carries GetHeader (metadata), every subsequent message
    carries GetChunk.
    """

    def Put(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List enumerates a namespace's artifacts as a stream of ArtifactMeta in
        ascending id order. Artifact is otherwise addressable only by known id;
        List lets an agent discover contents without an external index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.stream_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutRequest.FromString,
                    response_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetRequest.FromString,
                    response_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatRequest.FromString,
                    response_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteRequest.FromString,
                    response_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ListRequest.FromString,
                    response_serializer=memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ArtifactMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.artifact.v1.Artifact', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.artifact.v1.Artifact', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Artifact:
    """Artifact provides blob storage with metadata, scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".

    Put is client-streaming: the first message must carry PutInit, every
    subsequent message must carry PutChunk. Get is server-streaming: the
    first message carries GetHeader (metadata), every subsequent message
    carries GetChunk.
    """

    @staticmethod
    def Put(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/memsidecar.artifact.v1.Artifact/Put',
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutRequest.SerializeToString,
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memsidecar.artifact.v1.Artifact/Get',
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetRequest.SerializeToString,
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.artifact.v1.Artifact/Stat',
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatRequest.SerializeToString,
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.artifact.v1.Artifact/Delete',
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteRequest.SerializeToString,
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memsidecar.artifact.v1.Artifact/List',
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ListRequest.SerializeToString,
            memsidecar_dot_artifact_dot_v1_dot_artifact__pb2.ArtifactMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
