# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memsidecar/admin/v1/admin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'memsidecar/admin/v1/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmemsidecar/admin/v1/admin.proto\x12\x13memsidecar.admin.v1\"\x17\n\x15ListNamespacesRequest\"\x95\x01\n\x16ListNamespacesResponse\x12\x37\n\x06server\x18\x01 \x01(\x0b\x32\x1f.memsidecar.admin.v1.ServerInfoR\x06server\x12\x42\n\nnamespaces\x18\x02 \x03(\x0b\x32\".memsidecar.admin.v1.NamespaceInfoR\nnamespaces\">\n\nServerInfo\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x16\n\x06\x63ommit\x18\x02 \x01(\tR\x06\x63ommit\"\xe6\x01\n\rNamespaceInfo\x12\x14\n\x05\x62lock\x18\x01 \x01(\tR\x05\x62lock\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n\x07\x62\x61\x63kend\x18\x03 \x01(\tR\x07\x62\x61\x63kend\x12\x16\n\x06\x64river\x18\x04 \x01(\tR\x06\x64river\x12\x1d\n\nitem_count\x18\x05 \x01(\x03R\titemCount\x12\x1b\n\thas_count\x18\x06 \x01(\x08R\x08hasCount\x12=\n\x08\x65mbedder\x18\x07 \x01(\x0b\x32!.memsidecar.admin.v1.EmbedderInfoR\x08\x65mbedder\"`\n\x0c\x45mbedderInfo\x12\x1a\n\x08provider\x18\x01 \x01(\tR\x08provider\x12\x14\n\x05model\x18\x02 \x01(\tR\x05model\x12\x1e\n\ndimensions\x18\x03 \x01(\rR\ndimensions2r\n\x05\x41\x64min\x12i\n\x0eListNamespaces\x12*.memsidecar.admin.v1.ListNamespacesRequest\x1a+.memsidecar.admin.v1.ListNamespacesResponseB,Z*memsidecar/gen/memsidecar/admin/v1;adminv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memsidecar.admin.v1.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*memsidecar/gen/memsidecar/admin/v1;adminv1'
  _globals['_LISTNAMESPACESREQUEST']._serialized_start=56
  _globals['_LISTNAMESPACESREQUEST']._serialized_end=79
  _globals['_LISTNAMESPACESRESPONSE']._serialized_start=82
  _globals['_LISTNAMESPACESRESPONSE']._serialized_end=231
  _globals['_SERVERINFO']._serialized_start=233
  _globals['_SERVERINFO']._serialized_end=295
  _globals['_NAMESPACEINFO']._serialized_start=298
  _globals['_NAMESPACEINFO']._serialized_end=528
  _globals['_EMBEDDERINFO']._serialized_start=530
  _globals['_EMBEDDERINFO']._serialized_end=626
  _globals['_ADMIN']._serialized_start=628
  _globals['_ADMIN']._serialized_end=742
# @@protoc_insertion_point(module_scope)
