# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.admin.v1 import admin_pb2 as memsidecar_dot_admin_dot_v1_dot_admin__pb2


class AdminStub:
    """Admin exposes read-only server introspection: which namespaces exist, how
    they are configured, and their live item counts. It is cross-namespace and
    requires the admin.inspect op (no per-namespace scope is checked).

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNamespaces = channel.unary_unary(
                '/memsidecar.admin.v1.Admin/ListNamespaces',
                request_serializer=memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)


class AdminServicer:
    """Admin exposes read-only server introspection: which namespaces exist, how
    they are configured, and their live item counts. It is cross-namespace and
    requires the admin.inspect op (no per-namespace scope is checked).

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesRequest.FromString,
                    response_serializer=memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.admin.v1.Admin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.admin.v1.Admin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Admin:
    """Admin exposes read-only server introspection: which namespaces exist, how
    they are configured, and their live item counts. It is cross-namespace and
    requires the admin.inspect op (no per-namespace scope is checked).

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.admin.v1.Admin/ListNamespaces',
            memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesRequest.SerializeToString,
            memsidecar_dot_admin_dot_v1_dot_admin__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
