# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.lease.v1 import lease_pb2 as memsidecar_dot_lease_dot_v1_dot_lease__pb2


class LeaseStub:
    """Lease provides distributed locks scoped by namespace. A lease is identified
    by (namespace, key). Holders are fenced by a server-assigned holder_id —
    Renew and Release require it.

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.unary_unary(
                '/memsidecar.lease.v1.Lease/Acquire',
                request_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireRequest.SerializeToString,
                response_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.Renew = channel.unary_unary(
                '/memsidecar.lease.v1.Lease/Renew',
                request_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewRequest.SerializeToString,
                response_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewResponse.FromString,
                _registered_method=True)
        self.Release = channel.unary_unary(
                '/memsidecar.lease.v1.Lease/Release',
                request_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseResponse.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/memsidecar.lease.v1.Lease/Inspect',
                request_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectRequest.SerializeToString,
                response_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/memsidecar.lease.v1.Lease/List',
                request_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListRequest.SerializeToString,
                response_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListResponse.FromString,
                _registered_method=True)


class LeaseServicer:
    """Lease provides distributed locks scoped by namespace. A lease is identified
    by (namespace, key). Holders are fenced by a server-assigned holder_id —
    Renew and Release require it.

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    def Acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Renew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List returns every currently-held (unexpired) lease in a namespace.
        Inspect is single-key; List enables deadlock/orphan discovery and cleanup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireRequest.FromString,
                    response_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireResponse.SerializeToString,
            ),
            'Renew': grpc.unary_unary_rpc_method_handler(
                    servicer.Renew,
                    request_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewRequest.FromString,
                    response_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewResponse.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseRequest.FromString,
                    response_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseResponse.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectRequest.FromString,
                    response_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListRequest.FromString,
                    response_serializer=memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.lease.v1.Lease', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.lease.v1.Lease', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Lease:
    """Lease provides distributed locks scoped by namespace. A lease is identified
    by (namespace, key). Holders are fenced by a server-assigned holder_id —
    Renew and Release require it.

    Every RPC requires a capability token in the gRPC metadata key
    "x-memsidecar-capability" with value "Bearer <token>".
    """

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.lease.v1.Lease/Acquire',
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireRequest.SerializeToString,
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Renew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.lease.v1.Lease/Renew',
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewRequest.SerializeToString,
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.RenewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.lease.v1.Lease/Release',
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseRequest.SerializeToString,
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.lease.v1.Lease/Inspect',
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectRequest.SerializeToString,
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.lease.v1.Lease/List',
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListRequest.SerializeToString,
            memsidecar_dot_lease_dot_v1_dot_lease__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
