apiVersion: v1
kind: Service
metadata:
  name: {{ include "memsidecar.fullname" . }}
  labels:
    {{- include "memsidecar.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "memsidecar.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
    {{- if .Values.config.server.http.addr }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      appProtocol: http
    {{- end }}
    {{- if and .Values.config.observability.metrics (eq .Values.config.observability.metrics.exporter "prometheus") }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      appProtocol: http
    {{- end }}
