{{- if and .Values.serviceMonitor.enabled (eq .Values.config.observability.metrics.exporter "prometheus") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "memsidecar.fullname" . }}
  labels:
    {{- include "memsidecar.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "memsidecar.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.config.observability.metrics.prometheus.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
