# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mindd.episodic.v1 import episodic_pb2 as mindd_dot_episodic_dot_v1_dot_episodic__pb2


class EpisodicStub:
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-mindd-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/mindd.episodic.v1.Episodic/Append',
                request_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.SerializeToString,
                response_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Range = channel.unary_stream(
                '/mindd.episodic.v1.Episodic/Range',
                request_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.SerializeToString,
                response_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
                _registered_method=True)
        self.Tail = channel.unary_stream(
                '/mindd.episodic.v1.Episodic/Tail',
                request_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.SerializeToString,
                response_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
                _registered_method=True)
        self.Expire = channel.unary_unary(
                '/mindd.episodic.v1.Episodic/Expire',
                request_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireRequest.SerializeToString,
                response_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireResponse.FromString,
                _registered_method=True)


class EpisodicServicer:
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-mindd-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Range(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Expire(self, request, context):
        """Expire tombstones or physically removes events inside a bounded retention
        window (a cursor/time upper bound), in one server-side operation (U3).
        max_rows caps the affected set so maintenance stays localized. This is the
        log's retention/compaction path; per-event revision uses Append.supersedes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EpisodicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.FromString,
                    response_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.SerializeToString,
            ),
            'Range': grpc.unary_stream_rpc_method_handler(
                    servicer.Range,
                    request_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.FromString,
                    response_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.SerializeToString,
            ),
            'Tail': grpc.unary_stream_rpc_method_handler(
                    servicer.Tail,
                    request_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.FromString,
                    response_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.SerializeToString,
            ),
            'Expire': grpc.unary_unary_rpc_method_handler(
                    servicer.Expire,
                    request_deserializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireRequest.FromString,
                    response_serializer=mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mindd.episodic.v1.Episodic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mindd.episodic.v1.Episodic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Episodic:
    """Episodic is an append-only log of agent events scoped by namespace.
    Every RPC requires a capability token in the gRPC metadata key
    "x-mindd-capability" with value "Bearer <token>".

    Cursors are monotonic within a namespace. A reader can replay history
    (Range) or follow live (Tail) from any cursor.
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mindd.episodic.v1.Episodic/Append',
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendRequest.SerializeToString,
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Range(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mindd.episodic.v1.Episodic/Range',
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.RangeRequest.SerializeToString,
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mindd.episodic.v1.Episodic/Tail',
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.TailRequest.SerializeToString,
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Expire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mindd.episodic.v1.Episodic/Expire',
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireRequest.SerializeToString,
            mindd_dot_episodic_dot_v1_dot_episodic__pb2.ExpireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
