# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from memsidecar.kv.v1 import kv_pb2 as memsidecar_dot_kv_dot_v1_dot_kv__pb2


class KVStub(object):
    """KV provides typed, TTL'd key-value storage scoped by namespace.
    Every RPC requires a capability token carried in the gRPC metadata
    key "x-memsidecar-capability" with value "Bearer <token>".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/memsidecar.kv.v1.KV/Get',
                request_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetRequest.SerializeToString,
                response_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/memsidecar.kv.v1.KV/Put',
                request_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutRequest.SerializeToString,
                response_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/memsidecar.kv.v1.KV/Delete',
                request_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteRequest.SerializeToString,
                response_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_stream(
                '/memsidecar.kv.v1.KV/Scan',
                request_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.ScanRequest.SerializeToString,
                response_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.KVItem.FromString,
                _registered_method=True)


class KVServicer(object):
    """KV provides typed, TTL'd key-value storage scoped by namespace.
    Every RPC requires a capability token carried in the gRPC metadata
    key "x-memsidecar-capability" with value "Bearer <token>".
    """

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetRequest.FromString,
                    response_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutRequest.FromString,
                    response_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteRequest.FromString,
                    response_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteResponse.SerializeToString,
            ),
            'Scan': grpc.unary_stream_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.ScanRequest.FromString,
                    response_serializer=memsidecar_dot_kv_dot_v1_dot_kv__pb2.KVItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memsidecar.kv.v1.KV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memsidecar.kv.v1.KV', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KV(object):
    """KV provides typed, TTL'd key-value storage scoped by namespace.
    Every RPC requires a capability token carried in the gRPC metadata
    key "x-memsidecar-capability" with value "Bearer <token>".
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.kv.v1.KV/Get',
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetRequest.SerializeToString,
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.kv.v1.KV/Put',
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutRequest.SerializeToString,
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memsidecar.kv.v1.KV/Delete',
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteRequest.SerializeToString,
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memsidecar.kv.v1.KV/Scan',
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.ScanRequest.SerializeToString,
            memsidecar_dot_kv_dot_v1_dot_kv__pb2.KVItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
