{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "mindd.tlsSecretName" . }}
  labels:
    {{- include "mindd.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tls.cert required when tls.enabled is true and tls.existingSecret is empty" .Values.tls.cert | b64enc | quote }}
  tls.key: {{ required "tls.key required when tls.enabled is true and tls.existingSecret is empty" .Values.tls.key | b64enc | quote }}
  {{- if .Values.tls.clientCA }}
  ca.crt: {{ .Values.tls.clientCA | b64enc | quote }}
  {{- end }}
{{- end }}
